pkgs <- c("factoextra", "NbClust", "Hmisc, "Igraph","fBasicsp"")
library(Hmisc)
library(factoextra)
library(NbClust)
Pre_Crise <- read_excel("D:/Asus Pro/Google Drive/Acadêmicos/Dados/Pré Crise x Pos Crise -2 Anos/Pre Crise/Pre_Crise.xlsx", 
                        +     col_types = c("blank", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric", "numeric", 
                                            +         "numeric", "numeric"))
correlacao=rcorr(as.matrix(Pre_Crise), type="pearson")#Correlation Matrix
dist_cor=sqrt(2*(1-correlacao$r))#Distance Correlation Matrix
fviz_nbclust(dist_cor, hcut, method = "silhouette")+# Silhouette method
  labs(subtitle = "Silhouette Method")
#Gap statistic
set.seed(123)
fviz_nbclust(dist_cor, hcut, nstart = 25, method = "gap_stat", nboot = 50)+
  labs(subtitle = "Gap statistic method")
